# Generated by Django 3.2.15 on 2022-10-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=300)),
                ('op_1', models.CharField(max_length=50)),
                ('op_2', models.CharField(max_length=50)),
                ('op_3', models.CharField(max_length=50)),
                ('op_4', models.CharField(max_length=50)),
                ('correct_ans', models.IntegerField(max_length=10)),
            ],
        ),
    ]
