# Generated by Django 3.2.15 on 2022-10-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='correct_ans',
            field=models.IntegerField(),
        ),
    ]
