# Generated by Django 4.1.2 on 2022-11-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cg', '0002_alter_questions_correct_ans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='correct_ans',
            field=models.CharField(max_length=1),
        ),
    ]
