# Generated by Django 4.1.2 on 2022-11-17 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cg', '0003_alter_questions_correct_ans'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Questions',
            new_name='QuestionsFor10th',
        ),
    ]
