# Generated by Django 4.1.2 on 2022-11-17 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cg', '0004_rename_questions_questionsfor10th'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionsFor12th',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Question', models.CharField(max_length=300)),
                ('op_1', models.CharField(max_length=50)),
                ('op_2', models.CharField(max_length=50)),
                ('op_3', models.CharField(max_length=50)),
                ('op_4', models.CharField(max_length=50)),
                ('correct_ans', models.CharField(max_length=1)),
            ],
        ),
    ]
