# Generated by Django 4.1.2 on 2022-11-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cg', '0005_questionsfor12th'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionsfor10th',
            name='Q_name',
            field=models.CharField(default='q00', max_length=3),
        ),
        migrations.AddField(
            model_name='questionsfor12th',
            name='Q_name',
            field=models.CharField(default='q00', max_length=3),
        ),
    ]
